server:
    port: 8100
    #This is to allow the gateway proxy to access our swagger
    forward-headers-strategy: framework
spring:
    application:
        name: suivi_stage_d605
    docker:
    compose:
      enabled: true
      file: docker-compose.yml
    main:
        allow-circular-references: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                jdbc:
                    lob:
                        non_contextual_creation: true
    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/suivistagebd}
        username: admin
        password: admin123
        driver-class-name: org.postgresql.Driver
    mvc:
        dispatch-options-request: true

#Swagger-UI documentation
springdoc:
    api-docs:
        path: /suivistage-docs
    swagger-ui:
        path: /suivistage-doc.html
        
